spring.application.name=insurance-policy-management-system

spring.datasource.url=jdbc:mysql://capproj.mysql.database.azure.com/insurance_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=manisankar
spring.datasource.password=project@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mvc.cors.allowed-origins=http://localhost:4200,http://localhost:3000

spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
spring.mvc.cors.max-age=3600

logging.level.root=INFO
logging.level.com.example.insurance_policy_management_system=DEBUG